### ISSUE TITLE
Server side error. Don't know what it is

### ISSUE THREAD

**Issue by elie222** [arunoda/meteor-apm-client#37]
Hi,

I get the following error sometimes:
I20140516-11:03:25.529(3)? Exception from sub yE3Wfme9mj4ACBJbj TypeError: Cannot use 'in' operator to search for 'limit' in undefined
I20140516-11:03:25.530(3)?     at packages/underscore/underscore.js:860
I20140516-11:03:25.530(3)?     at Array.forEach (native)
I20140516-11:03:25.530(3)?     at _.each._.forEach (packages/underscore/underscore.js:105)
I20140516-11:03:25.530(3)?     at Function._.pick (packages/underscore/underscore.js:859)
I20140516-11:03:25.530(3)?     at Meteor.publish.Notifications.find.userId [as _handler](app/server/publications.js:181:26)
I20140516-11:03:25.530(3)?     at maybeAuditArgumentChecks (packages/livedata/livedata_server.js:1488)
I20140516-11:03:25.531(3)?     at _.extend._runHandler (packages/livedata/livedata_server.js:921)
I20140516-11:03:25.531(3)?     at _.extend._startSubscription (packages/livedata/livedata_server.js:771)
I20140516-11:03:25.531(3)?     at _.extend.protocol_handlers.sub (packages/livedata/livedata_server.js:584)
I20140516-11:03:25.532(3)?     at sessionProto.protocol_handlers.sub (packages/apm/lib/hijack/wrap_session.js:74)

Not sure what it is, but I can see it's coming from apm

**Comment by arunoda** [comment]
Hi,

It's not a direct APM issue. You see APM related file since we are
overriding some of the livedata apis.

Can you please check line #181 of your server/publication.js
That might be the issue.

Let me know, if that's not the issue.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it
out!http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by elie222** [comment]
That was the issue I believe. Thanks
