### ISSUE TITLE
Response time better expressed in seconds than 'k'

### ISSUE THREAD

**Issue by dandv** [arunoda/meteor-apm-client#42]
![image](https://cloud.githubusercontent.com/assets/33569/3015800/b7456734-df66-11e3-9013-b73e1a8429c1.png)

**Comment by arunoda** [comment]
That's actually millis. (we better indicate the measurement)

For most of the apps, Response Time below 1.5 seconds. That's why we keep
it as it is.
But let's see what we can do.
(May be we can try to change the axis values based on the data range)

---

Arunoda Susiripala
I curate Meteor Weekly - Check it
out!http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by dandv** [comment]
Right, setting the [yAxis.label.format](http://api.highcharts.com/highcharts#yAxis.labels.format) dynamically based on the `max`-`min` range would be nice.

**Comment by dandv** [comment]
Closing after moving to Kadira.
